# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  newman: postman/newman@0.0.2

jobs:
  node/test:
    docker:
      - image: circleci/node4.7
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  newman:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run: npm install
      - run: npm run newman

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - node/test
      - newman